.Dd May 1, 2020
.Dt TM1637 4
.Os
.Sh NAME
.Nm tm1637
.Nd driver for the TM1637
.Pa N Ns
-digits 7-segment display
.Sh SYNOPSIS
.Cd "kldload tm1637"
.Sh HARDWARE
The current version of the
.Nm
driver supports devices with one of the following
compatible strings :
.Pp
.Bl -bullet -compact
.It
tm1637-4-colon
.It
tm1637-6-dots
.El
.Sh DESCRIPTION
The
.Nm
is a low-cost 4(6)-digits 7-segment display module. It can display up to 4
(or 6) digits and a colon in the middle of the display or decimal dots after
each ones. Different variants of that types of the displays are used to display
numerical information or time. For a connecting to
.Xr gpiobus 4
it uses two wires CLK (scl) and DIO (sda) along with power (either +3V or +5V)
and GND. The device uses its own protocol for data exchange and does not comply
with the
.Xr iic 4
standard.
.Sh SYSCTL VARIABLES
The following variables are available to control the display via
.Xr sysctl 8 :
.Bd -literal -offset indent
dev.tm1637.0.on: 1
dev.tm1637.0.brightness: 1
dev.tm1637.0.%parent: simplebus0
dev.tm1637.0.%pnpinfo: name=tm1637@0 compat=tm1637-4-colon
dev.tm1637.0.%location: 
dev.tm1637.0.%driver: tm1637
dev.tm1637.0.%desc: TM1637 4 digit 7 segment display with colon
dev.tm1637.%parent: 
.Ed
.Bl -tag -width ".Va dev.tm1537"
.It Va dev.tm1637.<unit>.on
The mode of the display, 0=off, 1=on. In off mode display is blank and data
being written is not realy sent to it. But last piece of data will be sent
to the display when it is turned on. Any user can change this value.
.It Va dev.tm1637.<unit>.brightness
The display brightness level, 0=darkest, 7=brightest. Any user can change this
value.
.Sh NOTES
If Your platform is not FDT capable You can declare a display with
.Xr device.hints 5
file. For example, for a 4 digits display with colon coonected to pins
scl:26 and sda:29, add following strings to
.Pa /boot/device.hints :
.Bd -literal -offset indent
hint.tm1637.0.at="gpiobus0"
hint.tm1637.0.compatible="tm1637-4-colon"
hint.tm1637.0.pin_list="26 29"
hint.tm1637.0.scl="0"
hint.tm1637.0.sda="1"
.Ed
.Sh SEE ALSO
.Xr fdt 4 , Xr sysctl 8 , Xr device.hints 5
.Sh AUTHORS
.An -nosplit
The
.Nm
driver and this manual page were written by
.An Alexander Mishin Aq Mt mishin@mh.net.ru .
